language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
# command to install dependencies
install: 
  - pip install tox
# command to run tests
script: tox
env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=pypy
